name: code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
    - name: install tools
      run: |
        rustup component add llvm-tools-preview --toolchain nightly
        sudo apt-get install -y curl
        curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
    - name: llvm
      run: |
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Uploade coverage
      uses: codecov/codecov-action@v2
      with:
        files: lcov.info
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
