name: freebsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      uses: vmactions/freebsd-vm@v0.1.6
      with:
        usesh: true
        sync: rsync
        prepare: pkg install -y bash curl lang/rust devel/llvm-devel
        run: |
          cargo build --all --all-targets --verbose 
          curl https://sh.rustup.rs -sSf > rustup.sh
          sh rustup.sh -y
          . $HOME/.cargo/env
          rustup target add i686-unknown-freebsd
          cargo build --all --all-targets --verbose --target i686-unknown-freebsd
          
