name: freebsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v3
    - name: build
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        usesh: true
        sync: rsync
        copyback: false
        prepare: pkg install -y bash curl lang/rust devel/llvm-devel
        run: |
          cargo build --all --all-targets --verbose 
          cargo install cargo-deny
          cargo deny check licenses
          cargo deny check bans
          curl https://sh.rustup.rs -sSf > rustup.sh
          sh rustup.sh -y
          . $HOME/.cargo/env
          rustup target add i686-unknown-freebsd
          cargo build --all --all-targets --verbose --no-default-features --target i686-unknown-freebsd
          
