name: Release-plz

on:
  push:
    branches:
      - master

jobs:
  # Release unpublished packages if the latest commit merged
  # a release PR into master
  release:
    name: Publish a new release to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
