name: Cratesio Publish
on:
  workflow_dispatch:

  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publishing redismodule-rs-macros-internals
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: './redismodule-rs-macros-internals'
          args: --allow-dirty
          dry-run: true

      - name: Publishing redismodule-rs
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --allow-dirty
          dry-run: true

      - name: Publishing redismodule-rs-macros
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: './redismodule-rs-macros'
          args: --allow-dirty
          dry-run: true
