name: Test Registry Token

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test registry token login
        run: |
          echo "Testing cargo login with registry token..."
          # Use environment variable to avoid any risk of token exposure
          echo "$CARGO_REGISTRY_TOKEN" | cargo login
          echo "✅ Registry token login successful"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
